server:
  port: 8000
spring:
  application:
    name: microservice-provider-user
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: root123
  jpa:
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
# spring.application.name 指定注册到Eureka Server上的应用名称
# eureka.instance.prefer-ip-address 表示将自己的IP注册到Eureka Server；如不配，默认为false,则表示注册微服务所在操作系统的hostname到Eureka Server上
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true