server:
  port: 8000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: root123
  jpa:
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
##健康检查信息
##访问地址localhost:8000/actuator/health
## 访问地址localhost:8000/actuator/info
## 此处info是动态显示的目前没有做到
info:
  app:
    name: project.artifactid
    encoding: project.bulid.sourceEncoding
    java:
      source: java.version
      target: java.version
## 访问地址localhost:8000/actuator/metrics
## 访问地址localhost:8000/actuator/metrics/{name}
##每个健康检查信息对照参考此问档https://docs.spring.io/spring-boot/docs/2.0.6.RELEASE/reference/htmlsingle/#production-ready-endpoints-exposing-endpoints
management:
  endpoints:
    web:
      exposure:
        include: '*'