server:
  port: 8761
eureka:
  client:
    #表示是否将自己注册到EurekaServer,默认为true。由于当前应用就是EurekaServer,故而设为false
    register-with-eureka: false
    #表示是否从EurekaServer获取注册信息，默认为ture。因为这是一个单点的EurekaServer,不需要同步其他的EurekaServer节点的数据，故而设为false
    fetch-registry: false
    service-url:
      #设置EurekaServer交互地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka/；多个地址可使用','（即逗号）分割。
      defaultZone: http://localhost:8761/eureka/